name: Generate Call Graph

on:
  workflow_call:
    inputs:
      CONFIG_NAME:
        required: true
        type: string

env:
  ACTION_TMP: .github/actions-tmp                                              # 共通ワークフロー側
  CALLGRAPH: .github/actions-tmp/.github_automation/callgraph_enhanced/scripts # 共通ワークフロー側
  QUERIES: .github/codeql-queries

jobs:
  check-commits:
    runs-on: ubuntu-latest
    outputs:
      should-run: ${{ steps.check.outputs.should-run }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 50 # 過去のコミットを取得

      - name: Checkout shared github-actions repo ※共通ワークフロー側。こうしないと呼び出し元リポジトリ側の内容が上書きされて消える
        uses: actions/checkout@v4
        with:
          repository: cat2151/github-actions
          path: ${{ env.ACTION_TMP }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for user commits in last 24 hours
        id: check
        run: |
          node ${{ env.CALLGRAPH }}/check-commits.cjs

  generate-callgraph:
    needs: check-commits
    if: needs.check-commits.outputs.should-run == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      security-events: write
      actions: read

    steps:
      - name: Checkout repository ※呼び出し元リポジトリ側
        uses: actions/checkout@v4

      - name: Set Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Checkout shared github-actions repo ※共通ワークフロー側。こうしないと呼び出し元リポジトリ側の内容が上書きされて消える
        uses: actions/checkout@v4
        with:
          repository: cat2151/github-actions
          path: ${{ env.ACTION_TMP }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Node.js version
        run: |
          node ${{ env.CALLGRAPH }}/check-node-version.cjs

      - name: Install CodeQL CLI
        run: |
          wget https://github.com/github/codeql-cli-binaries/releases/download/v2.22.1/codeql-linux64.zip
          unzip codeql-linux64.zip
          sudo mv codeql /opt/codeql
          echo "/opt/codeql" >> $GITHUB_PATH

      - name: Install CodeQL query packs
        run: |
          /opt/codeql/codeql pack install ${{ env.QUERIES }}

      - name: Check CodeQL exists
        run: |
          node ${{ env.CALLGRAPH }}/check-codeql-exists.cjs

      - name: Verify CodeQL Configuration
        run: |
          node ${{ env.CALLGRAPH }}/analyze-codeql.cjs verify-config

      - name: Perform CodeQL Analysis
        run: |
          node ${{ env.CALLGRAPH }}/analyze-codeql.cjs analyze --overwrite

      - name: Check CodeQL Analysis Results
        run: |
          node ${{ env.CALLGRAPH }}/analyze-codeql.cjs check-results

      - name: Debug CodeQL execution
        run: |
          node ${{ env.CALLGRAPH }}/analyze-codeql.cjs debug

      - name: Wait for CodeQL results
        run: |
          node -e "setTimeout(()=>{}, 10000)"

      - name: Find and process CodeQL results
        run: |
          node ${{ env.CALLGRAPH }}/find-process-results.cjs

      - name: Generate HTML graph
        run: |
          node ${{ env.CALLGRAPH }}/generate-html-graph.cjs ${{ inputs.CONFIG_NAME }}

      - name: Copy files to generated-docs and commit results
        run: |
          node ${{ env.CALLGRAPH }}/copy-commit-results.cjs
