name: Call Rust fmt and Commit

on:
  push:
    paths:
      - '**/*.rs'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'rustfmt.toml'
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  call-rust-fmt:
    uses: ./.github/workflows/rust-fmt-commit.yml
    with:
      target-branch: ${{ github.ref_name }}
