# 過去24時間以内に人間のcommitがあるかどうかをチェックする
name: "Check recent human commit"

on:
  workflow_call:

jobs:
  check-recent-human-commit:
    runs-on: ubuntu-latest
    outputs:
      has_recent_human_commit: ${{ steps.check.outputs.has_recent_human_commit }}
    steps:
      - name: Checkout shared github-actions repo # ※呼び出し元ではなく、共通ワークフロー側
        uses: actions/checkout@v4
        with:
          repository: cat2151/github-actions
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check recent human commit
        id: check
        # このstepが GITHUB_OUTPUT を更新して、
        # jobのoutputsにマッピングされ、
        # 呼び出し元jobでは needs.<job_id>.outputs.has_recent_human_commit で参照される
        run: |
          node .github_automation/check_recent_human_commit/scripts/check-recent-human-commit.cjs
