# 過去24時間以内に人間のcommitがあるかどうかをチェックする
name: "Check recent human commit"

on:
  workflow_call:
    outputs:
      has_recent_human_commit:
        description: "Whether there is a recent human commit"
        value: ${{ jobs.check-recent-human-commit.outputs.has_recent_human_commit }}

jobs:
  check-recent-human-commit:
    runs-on: ubuntu-latest
    outputs:
      has_recent_human_commit: ${{ steps.check.outputs.has_recent_human_commit }}
    steps:
      - name: Checkout caller repository  # 呼び出し元リポジトリ。これがないと呼び出し元リポジトリのcommit履歴が得られない
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout shared github-actions repo # 共通ワークフローのリポジトリ。これがないとscriptを実行できない
        uses: actions/checkout@v4
        with:
          repository: cat2151/github-actions
          path: _shared-actions-temp
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check recent human commit
        id: check
        # cjs内で GITHUB_OUTPUT を更新している
        run: |
          node _shared-actions-temp/.github_automation/check_recent_human_commit/scripts/check-recent-human-commit.cjs
